### ISSUE TITLE
Cascade Validation does not work

### ISSUE THREAD

**Issue by rmed19** [craue/CraueFormFlowBundle#345]
Hi guys,

I have a form with an embed form on the second step. For the second step, the cascade validation does not work. to fix it I should force the validation_group to Default.

I did not understand why you force a new validation step and removing the Default one?

I create a PR #344 to add the validator default group.

**Comment by craue** [comment]
Not using the `Default` validation group is intended by design. This won't change.

Using the `Default` group on an entity with a standalone form is fine because you expect the entity to be filled with all required data and to be completely valid at that point. But when using a flow to stepwise fill an entity with data, it probably won't be completely valid after the 1st step (out of e.g. 5). Thus, a different validation group is used for each step. The reason for not using the `Default` group as well is to not trigger validation constraints already defined for other purposes.

If you really want (or need) to set custom validation groups, take a look at https://github.com/craue/CraueFormFlowBundle#validation-groups.
